### ISSUE TITLE
A few things to note

### ISSUE THREAD

**Issue by AakashKumarNain** [sayakpaul/Handwriting-Recognizer-in-Keras#1]
1. Let's drop all the punctuation marks for now. Punctuations like `,` or `.` are hard to differentiate for the model. We need to come up with a better solution for them
2. We don't need to use `cv2` or `imgaug` as the things that are implemented in the code can be implemented using TF image ops easily. It removes the external dependency on two libraries
3. Instead of tokenizer, we can use the `TextVectorization` layer.

**Comment by sayakpaul** [comment]
> Let's drop all the punctuation marks for now. Punctuations like , or . are hard to differentiate for the model. We need to come up with a better solution for them

Agreed. But given the number of occurrences of such characters in the current dataset I didn't see any problems. If weird problems start stemming we can always drop them. 

I can start working on the second one. Would you like to take the third one?

**Comment by AakashKumarNain** [comment]
Sure, I will take up the third one.

**Comment by sayakpaul** [comment]
Cool. I will drop a PR when I am done and ask for your review.

**Comment by sayakpaul** [comment]
@AakashKumarNain I tried porting the non-TF ops to pure TF but I ran into a problem during `distortion_free_resize()` since Tensor assignment is not supported. For now, I have ported most of the things apart from that one (which is realized with `tf.py_function()` for now). 

Here's the [Colab Gist](https://colab.research.google.com/gist/sayakpaul/ad2a3612ed657b86c90e928693b41217/scratchpad.ipynb) of how the preprocessing pipeline is looking currently.

#### Here is how the distortion-free resizing looks like:

![image](https://user-images.githubusercontent.com/22957388/129330086-0f3b7ff1-8440-4a36-92e9-10cd97d26522.png)

#### With vanilla `tf.image.resize()` (followed by a `tf.transpose()`):

![image](https://user-images.githubusercontent.com/22957388/129330524-a8bdc2d5-5290-4f06-a608-5d3fe178edf7.png)

Let me know your thoughts.

**Comment by AakashKumarNain** [comment]
Cool. Let me try to do that without `tf.py_function()`

**Comment by AakashKumarNain** [comment]
@sayakpaul one question for you: This is just resizing while keeping the aspect ratio same. Can't you use the [resize](https://www.tensorflow.org/api_docs/python/tf/image/resize) op directly?

**Comment by sayakpaul** [comment]
If we set `preserve_aspect_ratio=True` there then we don't have uniform image sizes anymore which won't be supported for mini-batching. So, `distortion_free_resize()` first ensures the aspect ratio is maintained to the highest dimension of the input image which is then copied to the desired shape.

**Comment by AakashKumarNain** [comment]
This should suffice your use case: 
https://colab.research.google.com/drive/1XVmtHNoY4__v786ynvPHmexj3-D-C6Bb?usp=sharing

**Comment by sayakpaul** [comment]
Thanks @AakashKumarNain. Looks much better than what I was doing. Do you want to pull this in during incorporating `TextVectorization`?

**Comment by AakashKumarNain** [comment]
@sayakpaul here is the complete input pipeline. Lemme know if this is good enough for your use case

https://colab.research.google.com/drive/1PV33aw5fI1CTZEJ6-jyYqv3JAKtYTEAY?usp=sharing

**Comment by sayakpaul** [comment]
@AakashKumarNain https://github.com/sayakpaul/Handwriting-Recognizer-in-Keras/pull/2
